name: flutter_typeahead
version: 1.7.1

description: A highly customizable typeahead (autocomplete) text input field for Flutter
homepage: https://github.com/AbdulRahmanAlHamali/flutter_typeahead
authors:
  - AbdulRahman AlHamali <a.alhamali93@gmail.com>
  - Kenneth Liang <kennethliang0@gmail.com>
  - Steven McDowall <sjm@hawoods.org>

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.5.0 <3.0.0'