import 'package:flutter_typeahead/src/common/typeahead/typeahead_form_field.dart';
import 'package:flutter_typeahead/src/material/typeahead_field.dart';

/// {@macro typeahead_field.TypeAheadFormField}
class TypeAheadFormField<T> extends RawTypeAheadFormField<T> {
  /// Creates a [TypeAheadFormField].
  TypeAheadFormField({
    super.key,
    super.animationDuration,
    super.autoFlipDirection,
    super.autoFlipListDirection,
    super.autoFlipMinHeight,
    super.builder,
    super.controller,
    super.debounceDuration,
    super.direction,
    super.errorBuilder,
    super.focusNode,
    super.hideKeyboardOnDrag,
    super.hideOnEmpty,
    super.hideOnError,
    super.hideOnLoading,
    super.hideOnUnfocus,
    super.hideWithKeyboard,
    super.hideOnSelect,
    required super.itemBuilder,
    super.itemSeparatorBuilder,
    super.keepSuggestionsOnLoading,
    super.loadingBuilder,
    super.minCharsForSuggestions,
    super.emptyBuilder,
    required super.onSelected,
    super.scrollController,
    super.suggestionsController,
    required super.suggestionsCallback,
    super.transitionBuilder,
    super.decorationBuilder,
    super.listBuilder,
    super.constraints,
    super.offset,
    super.initialValue,
    super.onReset,
    super.onSaved,
    super.validator,
    super.autovalidateMode,
    super.enabled,
  }) : super(
          fieldBuilder: (field) => TypeAheadField<T>(
            animationDuration: animationDuration,
            autoFlipDirection: autoFlipDirection,
            autoFlipListDirection: autoFlipListDirection,
            autoFlipMinHeight: autoFlipMinHeight,
            builder: builder,
            controller: controller,
            debounceDuration: debounceDuration,
            direction: direction,
            errorBuilder: errorBuilder,
            focusNode: focusNode,
            hideKeyboardOnDrag: hideKeyboardOnDrag,
            hideOnEmpty: hideOnEmpty,
            hideOnError: hideOnError,
            hideOnLoading: hideOnLoading,
            hideOnUnfocus: hideOnUnfocus,
            hideWithKeyboard: hideWithKeyboard,
            hideOnSelect: hideOnSelect,
            itemBuilder: itemBuilder,
            itemSeparatorBuilder: itemSeparatorBuilder,
            keepSuggestionsOnLoading: keepSuggestionsOnLoading,
            loadingBuilder: loadingBuilder,
            minCharsForSuggestions: minCharsForSuggestions,
            emptyBuilder: emptyBuilder,
            onSelected: onSelected,
            scrollController: scrollController,
            suggestionsController: suggestionsController,
            suggestionsCallback: suggestionsCallback,
            transitionBuilder: transitionBuilder,
            decorationBuilder: decorationBuilder,
            listBuilder: listBuilder,
            constraints: constraints,
            offset: offset,
          ),
        );
}
